[package]
name = "rrt"
version = "0.3.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
edition = "2018"
description = "Path finding using dual-RRT connect"
license = "Apache-2.0"
keywords = ["search", "path-finding", "rrt", "robotics"]
categories = ["algorithms"]
repository = "https://github.com/OTL/rrt"
documentation = "http://docs.rs/rrt"
readme = "README.md"

[dependencies]
kdtree = "0.6"
rand = "0.8"
log = "0.4"
env_logger = "0.8"
num-traits = "0.2"

[dev-dependencies]
nalgebra = "0.24"
ncollide3d = "0.27"
kiss3d = "0.29"
